sudo: required
services:
  - docker

before_install:
  - docker build -t paddyzab/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run paddyzab/react-test npm test -- --coverage

after_success:
  - docker build -t paddyzab/multi-client ./client
  - docker build -t paddyzab/multi-nginx ./nginx
  - docker build -t paddyzab/multi-server ./server
  - docker build -t paddyzab/multi-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push paddyzab/multi-client
  - docker push paddyzab/multi-nginx
  - docker push paddyzab/multi-server
  - docker push paddyzab/multi-worker